package com.skillstorm.practice.controllers;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/hello")
public class HelloController {
	// So far we've seen: Importing Spring Security 
	// - Written a very simple controller
	// - Seen that by default all the endpoints are locked down and require authentication
	// - The default authentication method is to force the user to a login page generated by the filter DefaultLoginPageGeneratingFilter
	
	@GetMapping
	public String hello() {
		return "Hello";
	}
	

}
