server:
  port: 8080
  
spring:
  application:
    name: recommendations-api
    
# remember each service needs to register itself with service discovery
# so tell it where to go register itself
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
#    register-with-eureka: false